version: '3.8'

services:

  webserver:
    build:
      dockerfile: ./Dockerfile

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 26379:6379
    # restart: always
    command: redis-server /home/local/conf/redis.conf
    volumes:
      - ./redis/data/:/data
      - ./redis/conf/redis.conf:/home/local/conf/redis.conf

  logdb:
    image: mongo:latest
    hostname: logdb
    container_name: logdb
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    ports:
      - 27016:27017
    command:
      - '--port'
      - '27017'
    volumes:
      - ./mongodb/data/db/replica/logdb:/data/db

  gamedb1:
    image: mongo:latest
    container_name: gamedb1
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data/db/replica/gamedb1:/data/db
    command:
      - '--port'
      - '27017'