version: '3.8'

services:
  keyStore:
    image: ubuntu:latest
    hostname: keyStore
    container_name: keyStore
    command: "openssl rand -base64 756 > /etc/mongodb.key && sudo chmod 400 /etc/mongodb.key"

#   mongo1:
#     image: mongo:latest
#     hostname: mongo1
#     container_name: mongo1
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root!
#     ports:
#       # 로컬 27017 포트로 요청이 들어오면 컨테이너의 27017 포트로 리다이렉트되도록 설정
#       - 27017:27017
#     volumes:
#       - ./data/db/replica/mongo1:/data/db
#       - keyStore:/etc/mongodb.key:/etc/mongodb.key 
      
#     # entrypoint: "chmod 400 /etc/mongodb.key"
#     # entrypoint: 
#     #       - bash
#     #       - -c
#     #       - |
#     #         chmod 400 /etc/mongodb.key 
#     command:
#       - '--replSet'
#       - 'myReplicaSet'
#       - '--keyFile'
#       - '/etc/mongodb.key'
#       - '--bind_ip_all'
#   mongo2:
#     image: mongo:latest
#     hostname: mongo2
#     container_name: mongo2
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root!
#     depends_on:
#       - mongo1
#     ports:
#       - 27018:27017
#     volumes:
#       - ./data/db/replica/mongo1:/data/db
#       -  keyStore:/etc/mongodb.key:/etc/mongodb.key 
#     # entrypoint: 
#     #       - bash
#     #       - -c
#     #       - |
#     #         chmod 400 /etc/mongodb.key 
#     command:
#       - '--replSet'
#       - 'myReplicaSet'
#       - '--keyFile'
#       - '/etc/mongodb.key'
#       - '--bind_ip_all'
#   mongo3:
#     image: mongo:latest
#     hostname: mongo3
#     container_name: mongo3
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root!
#     depends_on:
#       - mongo2
#     ports:
#       - 27019:27017
#     volumes:
#       - ./data/db/replica/mongo1:/data/db
#       -  keyStore:/etc/mongodb.key:/etc/mongodb.key 
      
#     # entrypoint: 
#     #       - bash
#     #       - -c
#     #       - |
#     #         chmod 400 /etc/mongodb.key 
#     command:
#       - '--replSet'
#       - 'myReplicaSet'
#       - '--keyFile'
#       - '/etc/mongodb.key'
#       - '--bind_ip_all'
# networks:
#   default:
#     name: mongoCluster
