version: '3.8'

services:

  webserver:
    build: 
      dockerfile: ./Dockerfile 

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    command: redis~-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/data/:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf

  
  logDb:
    image: mongo:latest
    hostname: logDb
    container_name: logDb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data/db/replica/logDb:/data/db
      - ./mongodb/etc/mongodb.key:/etc/mongodb.key 

  gameDb1:
    image: mongo:latest
    hostname: gameDb1
    container_name: gameDb1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data/db/replica/gameDb1:/data/db
      - ./mongodb/etc/mongodb.key:/etc/mongodb.key 
    command:
      - '--replSet'
      - 'myReplicaSet'
      - '--keyFile'
      - '/etc/mongodb.key'
      - '--bind_ip_all'
  gameDb2:
    image: mongo:latest
    hostname: gameDb2
    container_name: gameDb2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    depends_on:
      - gameDb1
    ports:
      - 27018:27017
    volumes:
      - ./mongodb/data/db/replica/gameDb2:/data/db
      - ./mongodb/etc/mongodb.key:/etc/mongodb.key 
    command:
      - '--replSet'
      - 'myReplicaSet'
      - '--keyFile'
      - '/etc/mongodb.key'
      - '--bind_ip_all'
  gameDb3:
    image: mongo:latest
    hostname: gameDb3
    container_name: gameDb3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    depends_on:
      - gameDb2
    ports:
      - 27019:27017
    volumes:
      - ./mongodb/data/db/replica/gameDb3:/data/db
      - ./mongodb/etc/mongodb.key:/etc/mongodb.key 
    command:
      - '--replSet'
      - 'myReplicaSet'
      - '--keyFile'
      - '/etc/mongodb.key'
      - '--bind_ip_all'
networks:
  default:
    name: mongoCluster
