version: '3.8'

services:

  webserver:
    build: 
      dockerfile: ./Dockerfile 

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - 26379:6379
    # restart: always
    command: redis-server /home/local/conf/redis.conf
    volumes:
      - ./redis/data/:/data
      - ./redis/conf/redis.conf:/home/local/conf/redis.conf

  
  logdb:
    image: mongo:latest
    hostname: logdb
    container_name: logdb
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    ports:
      - 27016:27017
    volumes:
      - ./mongodb/data/db/replica/logdb:/data/db

  gamedb1:
    image: mongo:latest
    hostname: gamedb1
    container_name: gamedb1
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data/db/replica/gamedb1:/data/db
      - /home/local/docker/mongodb/etc/mongodb.key:/etc/mongodb.key 
    command:
      - '--replSet'
      - 'gamedbreplicaset'
      - '--keyFile'
      - '/etc/mongodb.key'
      - '--bind_ip_all'
  gamedb2:
    image: mongo:latest
    hostname: gamedb2
    container_name: gamedb2
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    ports:
      - 27018:27018
    volumes:
      - ./mongodb/data/db/replica/gamedb2:/data/db
      - /home/local/docker/mongodb/etc/mongodb.key:/etc/mongodb.key 
    command:
      - '--replSet'
      - 'gamedbreplicaset'
      - '--keyFile'
      - '/etc/mongodb.key'
      - '--bind_ip_all'
  gamedb3:
    image: mongo:latest
    hostname: gamedb3
    container_name: gamedb3
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: haru
    ports:
      - 27019:27019
    volumes:
      - ./mongodb/data/db/replica/gamedb3:/data/db
      - /home/local/docker/mongodb/etc/mongodb.key:/etc/mongodb.key 
    command:
      - '--replSet'
      - 'gamedbreplicaset'
      - '--keyFile'
      - '/etc/mongodb.key'
      - '--bind_ip_all'
      
networks:
  default:
    name: gamedbreplicaset
